// AUTO-GENERATED by build-deps.mjs — do not edit by hand.
// Dependency versions + licenses, resolved from node_modules at build time.

export const EXT_INFO = {
  "name": "pkc2-graph-extension",
  "version": "0.1.0",
  "license": "AGPL-3.0",
  "builtAt": "2026-06-12",
  "dependencies": [
    {
      "name": "cytoscape",
      "version": "3.34.0",
      "license": "MIT"
    },
    {
      "name": "cytoscape-edgehandles",
      "version": "4.0.1",
      "license": "MIT"
    },
    {
      "name": "cytoscape-fcose",
      "version": "2.2.0",
      "license": "MIT"
    }
  ]
} as const;
