/**
 * @vitest-environment happy-dom
 *
 * Tests for the render-continuity helper (A-1 / A-2, 2026-04-23).
 *
 * The helper captures scroll / focus / caret state before a
 * full re-render and restores it after. These tests exercise
 * the helper directly (no full bootstrap) plus one end-to-end
 * assertion using `render()` so we verify the helper still works
 * against a real DOM generated by the renderer.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  captureRenderContinuity,
  restoreRenderContinuity,
} from '@adapter/ui/render-continuity';
import { render } from '@adapter/ui/renderer';
import type { AppState } from '@adapter/state/app-state';
import type { Container } from '@core/model/container';

let root: HTMLElement;

beforeEach(() => {
  root = document.createElement('div');
  root.id = 'pkc-root';
  document.body.appendChild(root);
});

afterEach(() => {
  root.remove();
});

// ── Unit tests on the helper ──

describe('captureRenderContinuity', () => {
  it('returns an empty snapshot when root is not attached', () => {
    const detached = document.createElement('div');
    const snap = captureRenderContinuity(detached);
    expect(snap.scrolls).toEqual([]);
    expect(snap.focus).toBeNull();
  });

  it('captures scrollTop from every known data-pkc-region scroller', () => {
    root.innerHTML = `
      <div data-pkc-region="sidebar" style="overflow:auto;height:50px"></div>
      <div data-pkc-region="center-content" style="overflow:auto;height:50px"></div>
      <div data-pkc-region="meta" style="overflow:auto;height:50px"></div>
    `;
    const sidebar = root.querySelector<HTMLElement>('[data-pkc-region="sidebar"]')!;
    const center = root.querySelector<HTMLElement>('[data-pkc-region="center-content"]')!;
    const meta = root.querySelector<HTMLElement>('[data-pkc-region="meta"]')!;
    // happy-dom lets us set scrollTop directly even without real
    // overflow content; good enough for this assertion.
    sidebar.scrollTop = 10;
    center.scrollTop = 120;
    meta.scrollTop = 5;

    const snap = captureRenderContinuity(root);
    const byRegion = Object.fromEntries(snap.scrolls.map((s) => [s.region, s.top]));
    expect(byRegion['sidebar']).toBe(10);
    expect(byRegion['center-content']).toBe(120);
    expect(byRegion['meta']).toBe(5);
  });

  it('skips scrollers at top (scrollTop === 0) so the snapshot stays small', () => {
    root.innerHTML = `
      <div data-pkc-region="sidebar"></div>
      <div data-pkc-region="center-content" style="overflow:auto;height:50px"></div>
    `;
    const center = root.querySelector<HTMLElement>('[data-pkc-region="center-content"]')!;
    center.scrollTop = 50;

    const snap = captureRenderContinuity(root);
    expect(snap.scrolls).toHaveLength(1);
    expect(snap.scrolls[0]!.region).toBe('center-content');
  });

  it('captures focus + caret for a focused input with data-pkc-field', () => {
    root.innerHTML = `
      <input type="text" data-pkc-field="search" value="hello" />
    `;
    const input = root.querySelector<HTMLInputElement>('[data-pkc-field="search"]')!;
    input.focus();
    input.setSelectionRange(2, 4);

    const snap = captureRenderContinuity(root);
    expect(snap.focus).not.toBeNull();
    expect(snap.focus!.field).toBe('search');
    expect(snap.focus!.caretStart).toBe(2);
    expect(snap.focus!.caretEnd).toBe(4);
  });

  it('returns null focus when the active element has no re-identification key', () => {
    // A button click leaves focus on the button; we deliberately
    // do NOT capture that — yanking focus back to a button after
    // a re-render creates the exact dizzying behavior the helper
    // is meant to prevent.
    root.innerHTML = `<button id="plain">Go</button>`;
    const btn = root.querySelector<HTMLButtonElement>('#plain')!;
    btn.focus();

    const snap = captureRenderContinuity(root);
    expect(snap.focus).toBeNull();
  });

  it('falls back to data-pkc-log-id when field is absent', () => {
    root.innerHTML = `
      <textarea data-pkc-log-id="log-42">body</textarea>
    `;
    const ta = root.querySelector<HTMLTextAreaElement>('[data-pkc-log-id]')!;
    ta.focus();
    ta.setSelectionRange(1, 1);
    const snap = captureRenderContinuity(root);
    expect(snap.focus).not.toBeNull();
    expect(snap.focus!.field).toBeNull();
    expect(snap.focus!.logId).toBe('log-42');
  });
});

describe('restoreRenderContinuity', () => {
  it('writes scrollTop back onto matching regions', () => {
    root.innerHTML = `
      <div data-pkc-region="center-content" style="overflow:auto;height:50px"></div>
    `;
    const center = root.querySelector<HTMLElement>('[data-pkc-region="center-content"]')!;
    restoreRenderContinuity(root, {
      scrolls: [{ region: 'center-content', top: 99 }],
      focus: null,
    });
    expect(center.scrollTop).toBe(99);
  });

  it('silently skips scroll regions that no longer exist', () => {
    // No `data-pkc-region` elements — restore must not throw.
    expect(() =>
      restoreRenderContinuity(root, {
        scrolls: [{ region: 'center-content', top: 40 }],
        focus: null,
      }),
    ).not.toThrow();
  });

  it('restores focus on an input matched by data-pkc-field', () => {
    root.innerHTML = `
      <input data-pkc-field="search" value="abcd" />
      <button>other</button>
    `;
    const input = root.querySelector<HTMLInputElement>('[data-pkc-field="search"]')!;
    // Start with focus elsewhere.
    root.querySelector<HTMLElement>('button')!.focus();
    expect(document.activeElement).not.toBe(input);

    restoreRenderContinuity(root, {
      scrolls: [],
      focus: { field: 'search', lid: null, logId: null, caretStart: 1, caretEnd: 3 },
    });

    expect(document.activeElement).toBe(input);
    expect(input.selectionStart).toBe(1);
    expect(input.selectionEnd).toBe(3);
  });

  it('handles hyphenated attribute values (real-world shape like tag-value)', () => {
    const value = 'saved-search-123';
    const input = document.createElement('input');
    input.setAttribute('data-pkc-field', value);
    root.appendChild(input);

    restoreRenderContinuity(root, {
      scrolls: [],
      focus: { field: value, lid: null, logId: null, caretStart: null, caretEnd: null },
    });
    expect(document.activeElement).toBe(input);
  });

  it('is a no-op when the snapshot has no focus and no scrolls', () => {
    root.innerHTML = `<input data-pkc-field="search" />`;
    const input = root.querySelector<HTMLInputElement>('input')!;
    expect(document.activeElement).not.toBe(input);
    restoreRenderContinuity(root, { scrolls: [], focus: null });
    expect(document.activeElement).not.toBe(input);
  });
});

// ── End-to-end: helper + renderer together ──

function makeContainer(): Container {
  return {
    meta: {
      container_id: 'rc-e2e',
      title: 'Render-continuity e2e',
      created_at: '2026-04-01T00:00:00.000Z',
      updated_at: '2026-04-01T00:00:00.000Z',
      schema_version: 1,
    },
    entries: [
      {
        lid: 'e1',
        title: 'Entry One',
        body: '# heading\n\n- [ ] task\n- [ ] another task\n\nlots of content '.repeat(30),
        archetype: 'text',
        created_at: '2026-04-01T00:00:00.000Z',
        updated_at: '2026-04-01T00:00:00.000Z',
      },
    ],
    relations: [],
    revisions: [],
    assets: {},
  };
}

function makeState(overrides: Partial<AppState> = {}): AppState {
  return {
    phase: 'ready',
    container: makeContainer(),
    selectedLid: 'e1',
    editingLid: null,
    error: null,
    embedded: false,
    pendingOffers: [],
    importPreview: null,
    batchImportPreview: null,
    searchQuery: '',
    archetypeFilter: new Set(),
    categoricalPeerFilter: null,
    sortKey: 'created_at',
    sortDirection: 'desc',
    exportMode: null,
    exportMutability: null,
    readonly: false,
    lightSource: false,
    showArchived: false,
    viewMode: 'detail',
    calendarYear: 2026,
    calendarMonth: 4,
    multiSelectedLids: [],
    batchImportResult: null,
    collapsedFolders: [],
    recentEntryRefLids: [],
    ...overrides,
  };
}

describe('render-continuity end-to-end with render()', () => {
  it('preserves center-content scrollTop across a full render() cycle', () => {
    const state = makeState();
    render(state, root);

    const center = root.querySelector<HTMLElement>('[data-pkc-region="center-content"]');
    expect(center).not.toBeNull();
    // Force a non-zero scroll — simulates the user having scrolled
    // down to tick a task partway through a long note.
    center!.scrollTop = 180;

    const snap = captureRenderContinuity(root);
    expect(snap.scrolls.find((s) => s.region === 'center-content')?.top).toBe(180);

    // Simulate the next dispatch: full re-render wipes root.
    render(makeState({ searchQuery: 'x' }), root);
    // Without the helper, center-content here is a brand-new node
    // with scrollTop = 0. Apply the snapshot.
    restoreRenderContinuity(root, snap);

    const centerAfter = root.querySelector<HTMLElement>('[data-pkc-region="center-content"]');
    expect(centerAfter!.scrollTop).toBe(180);
  });

  it('preserves focus + caret of the sidebar search input across a re-render', () => {
    render(makeState(), root);
    const search = root.querySelector<HTMLInputElement>('[data-pkc-field="search"]')!;
    search.focus();
    search.value = 'hi';
    search.setSelectionRange(2, 2);

    const snap = captureRenderContinuity(root);

    render(makeState({ searchQuery: 'hi' }), root);
    restoreRenderContinuity(root, snap);

    const after = root.querySelector<HTMLInputElement>('[data-pkc-field="search"]')!;
    expect(document.activeElement).toBe(after);
    expect(after.selectionStart).toBe(2);
    expect(after.selectionEnd).toBe(2);
  });
});
