/**
 * Inspector AI tab Phase 1 — local-only broken link summary(pgc-149)。
 *
 * pure features 層。entry.body の `entry:<lid>` 参照のうち target lid が
 * container に存在しない(broken)ものを Inspector に集約表示し、
 * quick-fix の起点とする。roadmap §2.2 A 群 3 / §3 Phase 1 完了。
 *
 * 既存の `buildLinkIndex(container).broken` を再利用、本 helper は
 * **current entry 単体 filter** + summary 化のみ。container 全体の
 * broken summary は References tab(pgc-108)に既存、本 helper は
 * AI tab 用の per-entry diagnostic。
 */

import type { Entry } from '../../core/model/record';
import type { Container } from '../../core/model/container';
import { buildLinkIndex } from '../link-index/link-index';

export interface BrokenLinkSummary {
  /** Stable id for dismiss UI. */
  id: string;
  /** Number of broken `entry:` references in this entry. */
  count: number;
  /** Sorted list of broken target lids (dedup'd). */
  brokenLids: readonly string[];
  /** Japanese human-readable reason for Inspector hint. */
  reason: string;
}

/**
 * Detect broken `entry:` references originating from `entry`. Returns
 * `null` when entry has no broken outgoing links. Stable for given
 * inputs (deterministic, no clock / network dependency).
 *
 * Excludes system entries (`system-*`) since their bodies are
 * generated by build scripts and broken-link warnings would be noise.
 */
export function detectBrokenLinkSummary(
  entry: Entry,
  container: Container,
): BrokenLinkSummary | null {
  if (entry.archetype.startsWith('system-')) return null;

  const index = buildLinkIndex(container);
  const brokenForEntry = index.broken.filter((b) => b.sourceLid === entry.lid);
  if (brokenForEntry.length === 0) return null;

  const set = new Set<string>();
  for (const b of brokenForEntry) set.add(b.targetLid);
  const sorted = Array.from(set).sort();

  return {
    id: `broken-links:${entry.lid}`,
    count: brokenForEntry.length,
    brokenLids: sorted,
    reason: sorted.length === 1
      ? `削除済 entry への参照 1 件:${sorted[0]} ── 本文修正 or 削除推奨`
      : `削除済 entry への参照 ${sorted.length} 件(${brokenForEntry.length} 箇所)── 本文修正 or 削除推奨`,
  };
}
