/**
 * Build step (mirrors PKC2's `about-entry-builder`): resolve each runtime
 * dependency's version + license from node_modules and emit a generated
 * `src/deps.generated.ts`, so the extension can show a dependency / version /
 * license panel — the same provenance the main PKC2 product surfaces in About.
 *
 * Wired as the first step of `npm run build`.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = dirname(fileURLToPath(import.meta.url));
const NM = resolve(dir, 'node_modules');
const pkg = JSON.parse(readFileSync(resolve(dir, 'package.json'), 'utf8'));

function readModule(name) {
  const p = resolve(NM, name, 'package.json');
  if (!existsSync(p)) return null;
  try { return JSON.parse(readFileSync(p, 'utf8')); } catch { return null; }
}
function licenseOf(name) {
  const m = readModule(name);
  if (!m) return 'unknown';
  if (typeof m.license === 'string' && m.license) return m.license;
  if (m.license && typeof m.license === 'object' && m.license.type) return m.license.type;
  if (Array.isArray(m.licenses) && m.licenses[0]?.type) return m.licenses[0].type;
  return 'unknown';
}
function versionOf(name, spec) {
  const m = readModule(name);
  return (m && m.version) || String(spec).replace(/^[\^~>=<\s]+/, '');
}

const dependencies = Object.entries(pkg.dependencies ?? {})
  .map(([name, spec]) => ({ name, version: versionOf(name, spec), license: licenseOf(name) }))
  .sort((a, b) => a.name.localeCompare(b.name));

const info = {
  name: pkg.name,
  version: pkg.version,
  license: pkg.license ?? 'unknown',
  builtAt: new Date().toISOString().slice(0, 10),
  dependencies,
};

const out =
  '// AUTO-GENERATED by build-deps.mjs — do not edit by hand.\n'
  + '// Dependency versions + licenses, resolved from node_modules at build time.\n\n'
  + `export const EXT_INFO = ${JSON.stringify(info, null, 2)} as const;\n`;

writeFileSync(resolve(dir, 'src/deps.generated.ts'), out);
console.log(`wrote src/deps.generated.ts (${dependencies.length} deps)`);
